# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-mf',
                'doc_host': 'https://kadeerkhan.github.io',
                'git_url': 'https://github.com/kadeerkhan/nbdev-mf',
                'lib_path': 'nbdev_mf'},
  'syms': {'nbdev_mf.core': {'nbdev_mf.core.foo': ('core.html#foo', 'nbdev_mf/core.py')}}}
